Repository qreate/spotify-playback-flutter, pull requests merged in 2019-04, with the labels that each got.

#18 Fixed: issue 15
  android/build.gradle
  example/android/app/build.gradle
  example/android/build.gradle
  example/android/gradle/wrapper/gradle-wrapper.properties
Labels: bug

#19 Added getImage and update README
  README.md
  android/src/main/kotlin/io/feesie/spotify/spotifyplayback/SpotifyPlaybackPlugin.kt
  example/lib/main.dart
  lib/spotify_playback.dart
Labels: enhancement, question, waiting for response

#26 Cleaned up code and refactored. And changed something to get image.
  .idea/vcs.xml
  .idea/workspace.xml
  CHANGELOG.md
  README.md
  android/src/main/kotlin/io/feesie/spotify/spotifyplayback/BaseControl.kt
  android/src/main/kotlin/io/feesie/spotify/spotifyplayback/ImageHandler.kt
  android/src/main/kotlin/io/feesie/spotify/spotifyplayback/PlaybackControls.kt
  android/src/main/kotlin/io/feesie/spotify/spotifyplayback/SeekControls.kt
  android/src/main/kotlin/io/feesie/spotify/spotifyplayback/SpotifyPlaybackPlugin.kt
  android/src/main/kotlin/io/feesie/spotify/spotifyplayback/spotifyGetImage.kt
  example/lib/credentials.dart
  example/lib/main.dart
  lib/spotify_playback.dart
  pubspec.yaml
  spotify_playback.iml
Labels: enhancement

#28 Add get auth token functionality
  android/build.gradle
  android/libs/spotify-auth-release-1.1.0.aar
  android/src/main/kotlin/io/feesie/spotify/spotifyplayback/SpotifyPlaybackPlugin.kt
  example/android/app/libs/spotify-auth-release-1.1.0.aar
  example/android/spotify-app-remote/build.gradle
  example/lib/main.dart
  lib/spotify_playback.dart
Labels: enhancement
